# Generated by Django 5.1.2 on 2024-10-17 13:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('tamaño_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_juegos', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Distribuidora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais_origen', models.CharField(default='Desconocido', max_length=100)),
                ('ingresos_anuales', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ColeccionBibliotecaJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Steam2.biblioteca')),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Steam2.coleccion')),
            ],
        ),
        migrations.AddField(
            model_name='coleccion',
            name='bibliotecas',
            field=models.ManyToManyField(through='Steam2.ColeccionBibliotecaJuego', to='Steam2.biblioteca'),
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_lanzamiento', models.DateTimeField(blank=True, null=True)),
                ('clasificacion_edad', models.IntegerField(choices=[(0, 'Todos'), (12, '12+'), (16, '16+'), (18, '18+')])),
                ('distribuidora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Steam2.distribuidora')),
            ],
        ),
        migrations.AddField(
            model_name='coleccionbibliotecajuego',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Steam2.juego'),
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ofertas', models.TextField()),
                ('oferta_semanal', models.DateField()),
                ('juegos', models.ManyToManyField(to='Steam2.juego')),
            ],
        ),
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_acumulados', models.IntegerField(default=0)),
                ('fecha_expiracion', models.DateTimeField()),
                ('nivel', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Steam2.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_conexion', models.DateTimeField(default=django.utils.timezone.now)),
                ('visibilidad', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Steam2.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_items', models.IntegerField(default=0)),
                ('total_precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Steam2.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Steam2.usuario'),
        ),
        migrations.CreateModel(
            name='Amigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_amistad', models.IntegerField()),
                ('interacciones_totales', models.IntegerField()),
                ('mensaje_personalizado', models.CharField(max_length=255)),
                ('usuarios', models.ManyToManyField(to='Steam2.usuario')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='coleccionbibliotecajuego',
            unique_together={('coleccion', 'biblioteca', 'juego')},
        ),
    ]
