# Generated by Django 5.1.2 on 2024-10-31 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Steam2', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coleccionbibliotecajuego',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='coleccionbibliotecajuego',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coleccionbibliotecajuego',
            name='fecha_adicion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='oferta_semanal',
            field=models.DateField(default='Sin ofertas'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='ofertas',
            field=models.TextField(default='Sin ofertas'),
        ),
    ]
