# Generated by Django 5.1.2 on 2024-11-02 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Steam2', '0002_alter_coleccionbibliotecajuego_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioPerfil', to='Steam2.usuario'),
        ),
    ]
