# Generated by Django 5.1.2 on 2024-11-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Steam2', '0003_alter_perfil_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleccion',
            name='bibliotecas',
            field=models.ManyToManyField(related_name='biblio', through='Steam2.ColeccionBibliotecaJuego', to='Steam2.biblioteca'),
        ),
    ]
