# Generated by Django 5.1.2 on 2024-11-03 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Steam2', '0004_alter_coleccion_bibliotecas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='Steam2.usuario'),
        ),
    ]
